service: webflask-auth

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:BatchGetItem"
        - "dynamodb:Describe*"
        - "dynamodb:Get*"
        - "dynamodb:ListStreams"
        - "dynamodb:ListTagsOfResource"
        - "dynamodb:Query"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
      Resource:
        - "arn:aws:dynamodb:ap-southeast-2:232293658217:table/webflask_users"
functions:
  index:
    handler: handler.index
    events:
      - http:
          path: /
          method: any
  login:
    handler: handler.login
    events:
      - http:
          path: /login 
          method: any
  register:
    handler: handler.register
    events:
      - http:
          path: /register 
          method: any